# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

configfile: "config/config.yaml"
include: "rules/common.smk"

# SUBMODULE_BLOCKS_PLACEHOLDER

rule all:
    default_target: True
    input:
        # ALL_INPUTS_PLACEHOLDER

include: "rules/other.smk"
